### ISSUE TITLE
Dependencias de Django

### ISSUE THREAD

**Issue by x3m1Sec** [mricharleon/HatosGanaderos#1]
![sin titulo](https://cloud.githubusercontent.com/assets/28686040/26033457/0026493a-38ad-11e7-8a2c-b14e4fb3fc29.jpg)
Hola Richar, he estado intentando probar tu proyecto. Como puedes ver en la imagen que adjunto, una vez levantado el Redis, el Nginx y nodeJS, lanzo el gunicorn con el siguiente comando dentro del entorno virtual obteniendo el siguiente error:

gunicorn -b 127.0.0.1:8000 wsgi
2017-05-14 04:22:55 [4749] [INFO] Starting gunicorn 17.5
2017-05-14 04:22:55 [4749] [INFO] Listening at: http://127.0.0.1:8000 (4749)
2017-05-14 04:22:55 [4749] [INFO] Using worker: sync
2017-05-14 04:22:55 [4754] [INFO] Booting worker with pid: 4754
2017-05-14 06:23:16 [4754] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_instance = mw_class()
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kpanic/HatosGanaderos/SIDGV/urls.py", line 8, in <module>
    admin.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 25, in autodiscover
    mod = import_module(app)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/guardian/__init__.py", line 5, in <module>
    from . import checks
  File "/usr/local/lib/python2.7/dist-packages/guardian/checks.py", line 2, in <module>
    from django.core.checks import register, Tags, Warning
ImportError: cannot import name register

Django version = 1.6.5 
Django-registration = 0.8

¿Sabes qué puede ser? 

Gracias.

Un saludo.

**Comment by mricharleon** [comment]
Que tal @kpanic8 perdona por la demora en la respuesta, primeramente por comentarte que es un proyecto que se ha descontinuado por X motivos, pero podemos probar con la versión de `gunicorn (version 19.3.0)` y ejecutando de la siguiente manera ` gunicorn --log-level debug SIDGV.wsgi:application -w3`
Y veamos que nos arroja.

Saludos

**Comment by x3m1Sec** [comment]
Hola @mricharleon. En primer lugar, agradecerte tu respuesta. He logrado resolver todas las dependencias que se especifican en el fichero settings.py en las INSTALLED_APPS.

Una vez logro levantar gunicorn con el comando que me has indicado, accedo a la pantalla principal de Hatos Ganaderos como puede verse:

![imagen](https://cloud.githubusercontent.com/assets/28686040/26118237/698bf9f2-3a69-11e7-8693-98828893ed9a.png)

Pero cuando intento registrarme o hacer login, obtengo el siguiente error:

![imagen](https://cloud.githubusercontent.com/assets/28686040/26118256/80fa1498-3a69-11e7-8014-60469f246541.png)

El fichero de log del nginx no me muestra ningún tipo de error y la consola del gunicorn tan sólo me muestra esto:

![imagen](https://cloud.githubusercontent.com/assets/28686040/26118272/931ce0a6-3a69-11e7-9ded-ff5e4dbaad84.png)

Además, en el fichero settings.py tengo configurada la IP local de mi máquina:
![imagen](https://cloud.githubusercontent.com/assets/28686040/26118352/df862b32-3a69-11e7-9e8b-69c020f4941b.png)

y el fichero default del site-enabled del nginx de la siguiente forma:

![imagen](https://cloud.githubusercontent.com/assets/28686040/26118405/114acc0e-3a6a-11e7-9dd7-a14600f310ef.png)

La consola del navegador me muestra error 404 de recurso no encontrado:

![imagen](https://cloud.githubusercontent.com/assets/28686040/26118672/017603d8-3a6b-11e7-90e4-aafbdc010496.png)


¿Sabes cuál puede ser el motivo?

De nuevo muchas gracias y un saludo.

**Comment by mricharleon** [comment]
Hola @kpanic8  he creado una nueva rama denominada `dev` y te pediría de favor que partamos de ella ya que he actualizado algunos archivos de settings, estilos, requirements, etc. Para ellos borrar la BD ya que en el README he agregado algunas líneas más a ejecutar y con ello esperemos no tener mayores inconvenientes.

**Comment by x3m1Sec** [comment]
Hola @mricharleon . He probado a realizar una instalación limpia siguiendo los nuevos pasos que has mencionado pero vuelvo a tener el mismo problema. Cuando ejecuto gunicorn y accedo a la dirección local localhost:8000 obtengo el siguiente error:

![imagen](https://cloud.githubusercontent.com/assets/28686040/26557162/92beb874-449f-11e7-91e0-46fb2d464bb6.png)

**Comment by mricharleon** [comment]
Que tal @kpanic8 en vista que la instalación es un tanto amplia, inicie la dockerizacion del proyecto para que sea sencillo la creación del entorno. 

- **Ahora ya puedes en pocos pasos tener el proyecto funcional.** Saludos

**Comment by x3m1Sec** [comment]
Hola @mricharleon. En primer lugar felicitarte por tu trabajo, tras la dockerización del proyecto es posible tener la aplicación funcionando en pocos pasos. El único problema que he encontrado testeando ha sido con el módulo de Registro. Me ha resultado imposible registrarme como nuevo usuario porque da un error en el servicio, tan sólo he podido ingresar con el usuario precargado admin/admin.

Gracias.

Un saludo.

**Comment by mricharleon** [comment]
Que tal @kpanic8,  podríamos intentar vaciar los contenedores 

`git pull origin master` (Por si acaso)
`docker-compose rm $(docker-compose ps -q)` (borra contenedores de compose)
`docker rm $(docker ps -a -q)` (borra los contenedores de docker)
`docker network rm $(docker network ls -q)` (borra las redes)
`docker rmi $(docker images -f "dangling=true" -q)` (borra imágenes none)
`docker volume rm $(docker volume ls -q)` (borra volúmenes)
`docker rmi hatosganaderos_hatosganaderos hatosganaderos_nginx hatosganaderos_db hatosganaderos_node -f` (borra imágenes de: app, db, nginx y node)

luego el procedimiento normal y a ver que sucede
`make start`
`make db`
`make spade`

Podríamos tratar estos temas en una sala que he creado para este proyecto [Gitter - HatosGanaderos](https://gitter.im/HatosGanaderos/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
